import React from 'react';
import { FileBarChart, Download, Calendar } from 'lucide-react';
import { useMockData } from '../context/MockDataContext';
import { SystemReport } from '../types';

const InvestorReports: React.FC = () => {
  const { reports } = useMockData();

  const handleDownloadPDF = (report: SystemReport) => {
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (printWindow) {
      const content = `
        <html>
          <head>
            <title>${report.title} - PDF Export</title>
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
              header { border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
              h1 { color: #1e293b; font-size: 24px; margin: 0 0 10px 0; }
              .meta { color: #64748b; font-size: 14px; }
              .badge { background: #f1f5f9; padding: 4px 8px; border-radius: 4px; font-weight: bold; text-transform: uppercase; font-size: 12px; }
              .content { line-height: 1.6; margin-bottom: 40px; }
              .footer { border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #94a3b8; text-align: center; }
              .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 80px; color: #f1f5f9; z-index: -1; font-weight: bold; }
            </style>
          </head>
          <body>
            <div class="watermark">CONFIDENTIAL</div>
            <header>
              <h1>${report.title}</h1>
              <div class="meta">
                <p><strong>Date:</strong> ${report.date} &nbsp;|&nbsp; <strong>Generated By:</strong> ${report.generatedBy}</p>
                <p><span class="badge">${report.type} REPORT</span></p>
              </div>
            </header>
            
            <div class="content">
              <h3>Executive Summary</h3>
              <p>This document serves as an official record for the <strong>${report.title}</strong>. It contains sensitive operational and financial data regarding the MediAccess biometric healthcare system.</p>
              
              <h3>Report Details</h3>
              <ul>
                <li><strong>Report ID:</strong> ${report.id}</li>
                <li><strong>Classification:</strong> Internal Use Only</li>
                <li><strong>File Size:</strong> ${report.size}</li>
              </ul>

              <h3>Analysis</h3>
              <p>
                The data contained within this report has been verified against the latest system logs and financial ledgers. 
                Growth metrics indicate a positive trend aligned with the Q3 projections. 
                ${report.type === 'Financial' ? 'Revenue streams from pilot institutions are stable, with a projected 15% increase in the next quarter.' : ''}
                ${report.type === 'Audit' ? 'System integrity checks passed with 99.9% uptime. No critical security vulnerabilities detected.' : ''}
              </p>
              
              <p><em>(Full detailed data tables and charts are attached in the supplementary appendix of the digital file.)</em></p>
            </div>

            <div class="footer">
              <p>MediAccess - Secure Healthcare Authentication Platform</p>
              <p>This document is confidential and intended solely for the addressee.</p>
            </div>
            
            <script>
              window.onload = function() { window.print(); }
            </script>
          </body>
        </html>
      `;
      printWindow.document.write(content);
      printWindow.document.close();
    }
  };

  return (
    <div className="p-8 max-w-7xl mx-auto animate-in fade-in duration-500">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Strategic Reports</h1>
        <p className="text-slate-500 mt-1">Financial statements, growth audits, and system performance logs.</p>
      </div>

      <div className="space-y-4">
        {reports.length === 0 ? (
           <div className="text-center py-12 bg-slate-50 rounded-2xl border border-dashed border-slate-200">
              <FileBarChart className="mx-auto h-12 w-12 text-slate-300 mb-2" />
              <p className="text-slate-500">No reports currently available.</p>
           </div>
        ) : reports.map((report) => (
            <div key={report.id} className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 flex items-center justify-between hover:bg-slate-50 hover:shadow-md hover:border-blue-200 transition-all duration-300 group">
                <div className="flex items-center gap-5">
                    <div className="w-14 h-14 bg-blue-50 rounded-xl flex items-center justify-center text-blue-600 group-hover:scale-105 transition-transform">
                        <FileBarChart size={28} />
                    </div>
                    <div>
                        <h3 className="font-bold text-lg text-slate-800 group-hover:text-blue-700 transition-colors">{report.title}</h3>
                        <div className="flex gap-4 text-xs font-medium text-slate-500 mt-1.5">
                            <span className="flex items-center gap-1.5"><Calendar size={14} /> {report.date}</span>
                            <span className={`px-2 py-0.5 rounded text-xs uppercase tracking-wide border ${
                                report.type === 'Financial' ? 'bg-emerald-50 text-emerald-700 border-emerald-100' :
                                report.type === 'Audit' ? 'bg-amber-50 text-amber-700 border-amber-100' :
                                report.type === 'Strategy' ? 'bg-purple-50 text-purple-700 border-purple-100' :
                                'bg-slate-100 text-slate-600 border-slate-200'
                            }`}>{report.type}</span>
                            <span className="text-slate-400">|</span>
                            <span>{report.size}</span>
                        </div>
                    </div>
                </div>
                <button 
                    onClick={() => handleDownloadPDF(report)}
                    className="flex items-center gap-2 px-5 py-2.5 border border-slate-200 rounded-xl text-sm font-semibold text-slate-600 hover:bg-blue-600 hover:border-blue-600 hover:text-white transition-all shadow-sm"
                >
                    <Download size={18} /> Download as PDF
                </button>
            </div>
        ))}
      </div>
    </div>
  );
};

export default InvestorReports;